In [1]:
import numpy as np

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)
zero_array = np.zeros((2,3))
print(zero_array)


[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]
[[ 6  5]
 [11  7]
 [ 4  8]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
one_array = np.ones((4,6))
print(one_array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [4]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)


[ 5  6  7  8  9 10 11]
[98 67 54 71 85 62]
[0.46940928 0.90457324 0.23323522 0.66058775 0.83401821 0.36721977]


In [5]:
random_Matrix = np.random.random((2,3))
print(random_Matrix)

[[0.92863135 0.87175702 0.78462653]
 [0.09116703 0.41814138 0.62140341]]


In [6]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[2.46940928 2.90457324 2.23323522 2.66058775 2.83401821 2.36721977]
[294 201 162 213 255 186]


## Task 1: Create a linear dataset
 Your goal is to create a simple dataset consisting of a single feature and a label as follows.
 1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature
 2. Assign 15 values to a NumPy array named label such that:

>label = (3)(feature) + 4

For example the first value for label should be

>label = (3)(6) + 4 = 22


In [7]:
feature = np.arange(6,21)
print(feature)
label = 3*feature + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [8]:
noise = 4* (np.random.random(15)-0.5)   
print(noise)
label = label+noise
print(label)

[-1.52782232  0.37512668  0.3809148   0.23703655  0.05321946  0.68556776
 -1.56434005  1.39693147 -0.20372056  1.81342561 -0.77819782 -0.29943339
 -0.77578101  0.3630202   1.48698698]
[20.47217768 25.37512668 28.3809148  31.23703655 34.05321946 37.68556776
 38.43565995 44.39693147 45.79627944 50.81342561 51.22180218 54.70056661
 57.22421899 61.3630202  65.48698698]


In [9]:

np.random.seed(21)
t3arr = np.random.randint(1, 501, (20,5))
t3arr = t3arr.astype(np.float32)

t3arr[:, 0] = (t3arr[:, 0])/t3arr[:, 0].max()
t3arr[:, 2] = (t3arr[:, 2])/t3arr[:, 2].max()
print(t3arr)
#np.random.seed(21)

[[9.4045174e-01 2.0800000e+02 6.8791211e-01 2.6100000e+02 4.9000000e+01]
 [7.5770020e-01 1.2100000e+02 9.2307693e-01 1.8900000e+02 9.9000000e+01]
 [4.9691993e-01 2.0300000e+02 7.2307694e-01 1.1100000e+02 4.4800000e+02]
 [8.8090348e-01 3.1800000e+02 5.5824178e-01 2.3400000e+02 2.5400000e+02]
 [5.0718683e-01 1.2300000e+02 6.7032969e-01 2.3900000e+02 3.5700000e+02]
 [1.0000000e+00 8.5000000e+01 6.9450551e-01 1.4900000e+02 3.7600000e+02]
 [4.2094457e-01 1.8500000e+02 3.7362638e-01 1.3400000e+02 4.8700000e+02]
 [4.7227925e-01 2.7500000e+02 1.0000000e+00 5.1000000e+01 4.4100000e+02]
 [4.8665297e-01 4.8300000e+02 1.0769231e-01 3.1000000e+02 2.6200000e+02]
 [1.6632444e-01 2.9200000e+02 8.1098902e-01 2.4900000e+02 4.7600000e+02]
 [8.5831624e-01 2.6900000e+02 5.2967036e-01 3.3900000e+02 2.7200000e+02]
 [8.0287474e-01 4.6900000e+02 7.6263738e-01 2.9000000e+01 1.3800000e+02]
 [9.5482546e-01 3.6600000e+02 8.4615386e-01 1.3400000e+02 3.2600000e+02]
 [4.8459959e-01 4.4200000e+02 2.6153848e-01 4.84000