In [ ]:
# Import Statements
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.animation as animation


In [ ]:

def createData():
    data = np.array([[5,10,1], [5,6,0], [-4,0,1], 
    [-5,-6,0], [4,8,1], [0,0,0], [-6,4,1], [4,0,0], 
    [2,-5,0], [4,-5,0], [-4,-3,0] ]).astype(float)
    data = np.c_[np.ones(data.shape[0]), data]
    x = data[:, 0:-1]
    y = data[:, -1]
    return x,y
#2 ********
def calcCost(X,W,Y):
    exponent = -1*np.dot(X,W)
    print(exponent)
    predictions = 1/(1+np.exp(exponent))
    predictions = np.reshape(predictions, Y.shape)
    costList = []
    for i in range(Y.size):
        if Y[i] == 0:
            costList.append(-np.log(1-predictions[i]))
        else:
            costList.append(-np.log(predictions[i]))
    cost = sum(costList)
    return cost

#3 ************ Complete the code that calculates 1/m * d/dw (cost function)
def calcGradient(X,W,Y):
    exponent = -1*np.dot(X,W)
    predictions = 1/(1+np.exp(exponent))
    cost = predictions-np.reshape(Y, (len(Y),1))    
    grad = 1/len(Y)*(np.dot(np.reshape(cost, (len(cost[0]), len(cost))), X))
    return np.reshape(grad, (len(grad[0]), 1))

#1b ********* Call and test the createData() function, create the weights array
# =============================================================================
# X,Y use createData method to create the X,Y matrices
# Weights - Create initial weight matrix (number of weights should be the same
# as the number of features)
# Weights - should be set to 0
# =============================================================================
#   

X,Y = createData()
numCols = len(X[0])
W = np.zeros((numCols, 1))

# set learning rate - the list is if we want to try multiple LR's
# We are only doing one of them today
lrList = [.3,.2]
lr = lrList[1]
#set up the cost array for graphing
costArray = []
costArray.append(calcCost(X, W, Y))
#initalize while loop flags
finished = False
count =0
print(calcCost(X,W,Y))
while (not finished and count <10000):
    gradient = calcGradient(X,W,Y)
    print
    #4 *********** update weights --------------------------------
    W = W - gradient*lr
    print("weights: ", W)
    print(calcCost(X,W,Y))
    costArray.append(calcCost(X, W, Y))
    lengthOfGradientVector = np.linalg.norm(gradient)
    if (lengthOfGradientVector < .0001):
        finished=True
    count+=1

# Create figure objects
fig = plt.figure()
ax = fig.add_axes([0.1,0.1,0.8,0.8])# [left, bottom, width, height]
ax.plot(np.arange(len(costArray)), costArray, "ro", label = "cost")
ax.set_title("Cost as weights are changed")
ax.set_xlabel("iteration")
ax.set_ylabel("Costs")
ax.legend()
plt.show()


[[ 1.  5. 10.]
 [ 1.  5.  6.]
 [ 1. -4.  0.]
 [ 1. -5. -6.]
 [ 1.  4.  8.]
 [ 1.  0.  0.]
 [ 1. -6.  4.]
 [ 1.  4.  0.]
 [ 1.  2. -5.]
 [ 1.  4. -5.]
 [ 1. -4. -3.]]
7.6246189861593985
weights:  [[-0.02727273]
 [-0.06363636]
 [ 0.31818182]]
4.795662527029524
weights:  [[-0.05938113]
 [-0.18471556]
 [ 0.32513213]]
4.129875199132529
weights:  [[-0.09093131]
 [-0.24441449]
 [ 0.35855456]]
3.8520205985489304
weights:  [[-0.12192177]
 [-0.28508683]
 [ 0.39043294]]
3.6669334221085874
weights:  [[-0.15246285]
 [-0.3177638 ]
 [ 0.41680742]]
3.5267752069780176
weights:  [[-0.18256443]
 [-0.34520469]
 [ 0.43925754]]
3.412879057519038
weights:  [[-0.21223038]
 [-0.36890163]
 [ 0.45882567]]
3.31596528815047
weights:  [[-0.24146357]
 [-0.38978544]
 [ 0.4761919 ]]
3.230859802096944
weights:  [[-0.27026705]
 [-0.40847957]
 [ 0.49182461]]
3.1544320942075834
weights:  [[-0.29864437]
 [-0.42542339]
 [ 0.50606079]]
3.0846672321347395
weights:  [[-0.3265997 ]
 [-0.44093878]
 [ 0.51915124]]
3.0202032105592

KeyboardInterrupt: 