In [4]:

# Import Statements
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.animation as animation


data = np.array([[5,10,1], [5,6,0], [-4,0,1], 
[-5,-6,0], [4,8,1], [0,0,0], [-6,4,1], [4,0,0], 
[2,-5,0], [4,-5,0], [-4,-3,0] ]).astype(float)
data = np.c_[np.ones(data.shape[0]), data]
X = data[:, 0:-1]
Y = data[:, -1]
W = [0,0,0]

exponent = -1*np.dot(X,W)
predictions = 1/(1+np.exp(exponent))
predictions = np.reshape(predictions, Y.shape)
costList = []
for i in range(Y.size):
    if Y[i] == 0:
        costList.append(-np.log(1-predictions[i]))
    else:
        costList.append(-np.log(predictions[i]))
cost = sum(costList)



exponent = -1*np.dot(X,W)
predictions = 1/(1+np.exp(exponent))
cost = predictions-np.reshape(Y, (len(Y),1))    
grad = 1/len(Y)*(np.dot(np.reshape(cost, (len(cost[0]), len(cost))), X))
print(grad)



[[-0.5        -0.22727273 -0.40909091]
 [ 0.5         0.22727273  0.40909091]
 [-0.5        -0.22727273 -0.40909091]
 [ 0.5         0.22727273  0.40909091]
 [-0.5        -0.22727273 -0.40909091]
 [ 0.5         0.22727273  0.40909091]
 [-0.5        -0.22727273 -0.40909091]
 [ 0.5         0.22727273  0.40909091]
 [ 0.5         0.22727273  0.40909091]
 [ 0.5         0.22727273  0.40909091]
 [ 0.5         0.22727273  0.40909091]]
